name: liveboard
recipe: lamp
config:
  php: '8.0'
  composer_version: 2-latest
  webroot: ./
  database: mariadb
  xdebug: true
proxy:
  mailing:
    - mail.landomailhog.lndo.site
services:
  appserver:
    type: php
    build_as_root:
      - docker-php-ext-install sockets
    ports:
      - 8000-8100:8000-8100
    appserver:
      - external

  pma:
    type: phpmyadmin
    hosts:
      - database

  mailing:
    type: mailhog
    portforward: true
    hogfrom:
      - appserver

bindAddress: "0.0.0.0"

